### ISSUE TITLE
Results?

### ISSUE THREAD

**Issue by XinWangg** [Hanan-Li/masked-face-recognition#1]
Can you share your test results on multiple test datasets?

**Comment by Hanan-Li** [comment]
I'll get back to you with the results within 2 days, its stored on an old machine.

**Comment by Hanan-Li** [comment]
Sorry for the late reply. I completely forgot about this.

For context, this is a school project. I've uploaded our report that contains all the information and results.

[Group4-Masked Face Verification-Report.pdf](https://github.com/Hanan-Li/masked-face-recognition/files/6837579/Group4-Masked.Face.Verification-Report.pdf)
